import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  include: ["./src/**/*.{js,jsx,ts,tsx}", "./pages/**/*.{js,jsx,ts,tsx}"],
  exclude: [],
  theme: {
    extend: {
      tokens: {
        colors: {
          "inverse-on-surface": { value: "#eaf1ff" },
          secondary: { value: "#515f78" },
          outline: { value: "#737687" },
          "surface-container-high": { value: "#dce9ff" },
          "on-error-container": { value: "#93000a" },
          "on-background": { value: "#0b1c30" },
          "surface-container-low": { value: "#eff4ff" },
          "surface-container-highest": { value: "#d3e4fe" },
          tertiary: { value: "#005f75" },
          "primary-fixed-dim": { value: "#b4c5ff" },
          "surface-dim": { value: "#cbdbf5" },
          "on-tertiary-container": { value: "#e3f6ff" },
          "secondary-fixed-dim": { value: "#b9c7e4" },
          "on-surface": { value: "#0b1c30" },
          "surface-container-lowest": { value: "#ffffff" },
          background: { value: "#f8f9ff" },
          "surface-container": { value: "#e5eeff" },
          "primary-fixed": { value: "#dbe1ff" },
          "tertiary-fixed-dim": { value: "#4cd6ff" },
          "on-secondary": { value: "#ffffff" },
          "surface-variant": { value: "#d3e4fe" },
          "secondary-fixed": { value: "#d6e3ff" },
          "inverse-primary": { value: "#b4c5ff" },
          surface: { value: "#f8f9ff" },
          "tertiary-fixed": { value: "#b7eaff" },
          "tertiary-container": { value: "#007995" },
          "on-tertiary-fixed": { value: "#001f28" },
          error: { value: "#ba1a1a" },
          "on-tertiary-fixed-variant": { value: "#004e60" },
          "on-tertiary": { value: "#ffffff" },
          "on-primary-container": { value: "#f1f2ff" },
          primary: { value: "#004bca" },
          "inverse-surface": { value: "#213145" },
          "surface-bright": { value: "#f8f9ff" },
          "on-secondary-fixed": { value: "#0d1c32" },
          "on-primary-fixed": { value: "#00174b" },
          "outline-variant": { value: "#c2c6d9" },
          "on-primary-fixed-variant": { value: "#003ea8" },
          "primary-container": { value: "#0061ff" },
          "surface-tint": { value: "#0052dc" },
          "error-container": { value: "#ffdad6" },
          "on-secondary-fixed-variant": { value: "#39475f" },
          "on-surface-variant": { value: "#424656" },
          "secondary-container": { value: "#d2e0fe" },
          "on-primary": { value: "#ffffff" },
          "on-secondary-container": { value: "#55637d" },
          "on-error": { value: "#ffffff" },
          white: { value: "#ffffff" },
        },
        spacing: {
          unit: { value: "4px" },
          xs: { value: "4px" },
          sm: { value: "8px" },
          md: { value: "16px" },
          lg: { value: "24px" },
          xl: { value: "32px" },
          "2xl": { value: "48px" },
          "3xl": { value: "64px" },
          gutter: { value: "24px" },
          full: { value: "100%" },
        },
        sizes: {
          full: { value: "100%" },
          fit: { value: "fit-content" },
          "container-max": { value: "1280px" },
          "600px": { value: "600px" },
        },
        radii: {
          DEFAULT: { value: "0.25rem" },
          lg: { value: "0.5rem" },
          xl: { value: "0.75rem" },
          full: { value: "9999px" },
        },
        fonts: {
          "label-caps": { value: "Inter, sans-serif" },
          "body-lg": { value: "Inter, sans-serif" },
          "headline-lg": { value: "Geist, sans-serif" },
          "display-lg": { value: "Geist, sans-serif" },
          "body-md": { value: "Inter, sans-serif" },
          "headline-lg-mobile": { value: "Geist, sans-serif" },
          "headline-md": { value: "Geist, sans-serif" },
          "code-md": { value: "JetBrains Mono, monospace" },
          "body-sm": { value: "Inter, sans-serif" },
        },
        fontSizes: {
          "label-caps": { value: "12px" },
          "body-lg": { value: "18px" },
          "headline-lg": { value: "32px" },
          "display-lg": { value: "48px" },
          "body-md": { value: "16px" },
          "headline-lg-mobile": { value: "24px" },
          "headline-md": { value: "24px" },
          "body-sm": { value: "14px" },
          "code-md": { value: "14px" },
        },
        lineHeights: {
          "label-caps": { value: "16px" },
          "body-lg": { value: "28px" },
          "headline-lg": { value: "40px" },
          "display-lg": { value: "56px" },
          "body-md": { value: "24px" },
          "headline-lg-mobile": { value: "32px" },
          "headline-md": { value: "32px" },
          "body-sm": { value: "20px" },
          "code-md": { value: "20px" },
        },
        fontWeights: {
          "label-caps": { value: "600" },
          medium: { value: "500" },
          semibold: { value: "600" },
          bold: { value: "700" },
        },
        shadows: {
          sm: { value: "0 1px 3px rgba(11, 28, 48, 0.10)" },
          md: { value: "0 8px 24px rgba(11, 28, 48, 0.12)" },
          lg: { value: "0 16px 40px rgba(11, 28, 48, 0.16)" },
        },
        blurs: {
          md: { value: "12px" },
        },
      },
    },
  },
  outdir: "styled-system",
});
